数据处理：numpy, pandas
画图：matplotlib

# 一、numpy

列表可以存储任意多钟类型的数据，数组的元素类型必须相同

In [1]:
import array
import numpy as np

In [2]:
#从原有列表转换为数组
a_list = list(range(10))
b = np.array(a_list)
type(b)

numpy.ndarray

In [14]:
#生成数组
a = np.zeros((4,4),dtype = int)
type(a), a.dtype,  a

(numpy.ndarray, dtype('int32'), array([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]))

In [13]:
np.ones((4,4),dtype = float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
np.full((3,3),3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [17]:
np.full_like(a,3)   #仿造a的格式生成

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [18]:
np.random.random((3,3))

array([[0.08828778, 0.78160009, 0.33984489],
       [0.13479486, 0.56156218, 0.03491277],
       [0.33373878, 0.00396539, 0.26844194]])

In [19]:
np.random.randint(0,10,(5,5))

array([[4, 9, 1, 5, 6],
       [4, 3, 9, 7, 6],
       [7, 2, 0, 6, 4],
       [7, 9, 3, 9, 5],
       [9, 4, 1, 0, 0]])

In [21]:
#范围取值
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [23]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [24]:
#生成单位矩阵
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])